#!/bin/sh

getfattr -d -R $1 | while read -r line
do
  case $line in
            "# file: "*) filename=${line#"# file: "}
                         exec=0
                         load=0
                         owner=0
                         perm=13
                         ;;
     user.econet_exec=*) exec=${line#*\"}; exec=${exec%\"} ;;
     user.econet_load=*) load=${line#*\"}; load=${load%\"} ;;
    user.econet_owner=*) owner=${line#*\"}; owner=${owner%\"} ;;
     user.econet_perm=*) perm=${line#*\"}; perm=${perm%\"} ;;
                     "") echo "$owner $load $exec $perm" > $filename.inf
  esac
done
